# Generated by Django 4.1.3 on 2022-12-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0003_accountwallet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountwallet',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
