# Generated by Django 4.1.3 on 2022-12-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0004_accountwallet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountwallet',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
