# Generated by Django 4.1.3 on 2022-12-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0005_alter_accountwallet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountwallet',
            name='name',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
