# Generated by Django 4.1.3 on 2022-12-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0006_alter_accountwallet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountwallet',
            old_name='name',
            new_name='_name',
        ),
    ]
