# Generated by Django 4.1.3 on 2022-12-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=8)),
                ('receiver', models.CharField(max_length=8)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Количество денег на перевод')),
                ('commision', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Комиcсия')),
                ('status', models.BooleanField(blank=True, default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
